// Generated by Wrangler by running `wrangler types`

// NOT USING THIS
export async function getBindings() {
    if (import.meta.env.DEV) {
      const wrangler = await import('wrangler');
      const { env } = await wrangler.getPlatformProxy<Env>();
      return env;
    }
  
    return process.env as unknown as Env;
}