/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DeferedImport } from './routes/defered'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DeferedRoute = DeferedImport.update({
  id: '/defered',
  path: '/defered',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/defered': {
      id: '/defered'
      path: '/defered'
      fullPath: '/defered'
      preLoaderRoute: typeof DeferedImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/defered': typeof DeferedRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/defered': typeof DeferedRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/defered': typeof DeferedRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/defered'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/defered'
  id: '__root__' | '/' | '/defered'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeferedRoute: typeof DeferedRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeferedRoute: DeferedRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/defered"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/defered": {
      "filePath": "defered.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
